--- #YAML:1.0
name: DBIx-Admin-TableInfo
version: 1.03
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  A wrapper around DBI's table_info() and column_info()
license: artistic
requires:
  Carp: 0
  DBI: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides:
  DBIx::Admin::TableInfo:
    file: lib/DBIx/Admin/TableInfo.pm
    version: 1.03
generated_by: Module::Build version 0.2611
