--- #YAML:1.0
name: DBIx-Admin-TableInfo
version: 1.02
author:
  - Ron Savage <ron@savage.net.au>
abstract: |-
  A wrapper around DBI's table_info() and column_info()
license: artistic
requires:
  Carp: 0
  DBI: 0
build_requires:
  Test::More: 0
  Test::Pod: 0
provides: {}
generated_by: Module::Build version 0.24
